services:
    Imper86\DDD\Domain\Bus\Command\CommandBus:
        class: Imper86\DddBundle\Bus\MessengerCommandBus
        arguments:
            $commandBus: '@command.bus'

    Imper86\DDD\Domain\Bus\Event\EventBus:
        class: Imper86\DddBundle\Bus\MessengerEventBus
        arguments:
            $eventBus: '@event.bus'

    Imper86\DDD\Domain\Bus\Query\QueryBus:
        class: Imper86\DddBundle\Bus\MessengerQueryBus
        arguments:
            $queryBus: '@query.bus'
