services:
    _defaults:
        autowire: true
        autoconfigure: true

    Imper86\DDD\Domain\Bus\Command\CommandBus:
        class: Imper86\DddBundle\Bus\MessengerCommandBus

    Imper86\DDD\Domain\Bus\Event\EventBus:
        class: Imper86\DddBundle\Bus\MessengerEventBus

    Imper86\DDD\Domain\Bus\Query\QueryBus:
        class: Imper86\DddBundle\Bus\MessengerQueryBus

    command.bus:
        class: Symfony\Component\Messenger\MessageBus
        tags: [messenger.bus]

    event.bus:
        class: Symfony\Component\Messenger\MessageBus
        tags: [messenger.bus]

    query.bus:
        class: Symfony\Component\Messenger\MessageBus
        tags: [messenger.bus]
